# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('game_imageUrl', models.CharField(max_length=200)),
                ('game_url', models.CharField(max_length=200)),
            ],
        ),
    ]
