# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_imageUrl',
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(default='12', height_field='game_image_height', upload_to='media/', width_field='game_image_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_image_height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_image_width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
