# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0002_auto_20170917_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='TzarioGames.Category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('game_added_date',)},
        ),
        migrations.AddField(
            model_name='game',
            name='game_added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
