# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0003_auto_20170920_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(to='TzarioGames.Category'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_tag',
            field=models.ManyToManyField(to='TzarioGames.Tag'),
        ),
    ]
