# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0004_auto_20171016_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
