# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0005_remove_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_tag',
        ),
    ]
