# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0006_auto_20171023_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TzarioGames.Category'),
            preserve_default=False,
        ),
    ]
