# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TzarioGames', '0007_game_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
